FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /bin/server ./cmd/server && go clean -cache -modcache

FROM alpine:3.18
COPY --from=builder /bin/server /server
COPY migrations /migrations
EXPOSE 8081
CMD ["/server"]